import { mysqlTable, serial, varchar, int, text, boolean } from "drizzle-orm/mysql-core";
import type { InferSelectModel } from "drizzle-orm";

export const accident = mysqlTable("accident", {
    id: varchar("id", { length: 255 }).primaryKey(),
    happen_date: varchar("happen_date", { length: 255 }).notNull(),
    month: varchar("month", { length: 255 }).notNull(),
    oa_number: varchar("oa_number", { length: 255 }).notNull(),
    oa_submit_date: varchar("oa_submit_date", { length: 255 }).notNull(),
    product_line: varchar("product_line", { length: 255 }).notNull(),
    detail_place: varchar("detail_place", { length: 255 }).notNull(),
    self_ignite_cell_type: varchar("self_ignite_cell_type", { length: 255 }).notNull(),
    self_ignite_cell_number: varchar("self_ignite_cell_number", { length: 255 }).notNull(),
    battery_self_ignite_reason: varchar("battery_self_ignite_reason", { length: 500 }).notNull(),
    detail_content: text("detail_content").notNull(),
    accident_or_event: varchar("accident_or_event", { length: 50 }).notNull(),
    accident_cause: varchar("accident_cause", { length: 500 }),
    accident_type: varchar("accident_type", { length: 255 }),
    economic_loss: varchar("economic_loss", { length: 255 }),
    work_hours_loss: varchar("work_hours_loss", { length: 255 }),
    accident_level: varchar("accident_level", { length: 50 }),
    internal_or_related: varchar("internal_or_related", { length: 50 }),
    is_traffic_accident: boolean("is_traffic_accident").default(false),
    is_fire_event: boolean("is_fire_event").default(false),
    is_smoke_fire_attempt: boolean("is_smoke_fire_attempt").default(false),
    event_cause: varchar("event_cause", { length: 500 }),
    event_type: varchar("event_type", { length: 255 }),
    event_economic_loss: varchar("event_economic_loss", { length: 255 }),
    attempt_classification: varchar("attempt_classification", { length: 255 }),
    direct_cause_type: varchar("direct_cause_type", { length: 255 }),
    detail_content1: text("detail_content1"),
    indirect_cause_type: varchar("indirect_cause_type", { length: 255 }),
    detail_content2: text("detail_content2"),
    system_cause_type: varchar("system_cause_type", { length: 255 }),
    detail_content3: text("detail_content3"),
    corrective_measures: text("corrective_measures"),
    completion_status: varchar("completion_status", { length: 255 }),
    is_responsible_accident: boolean("is_responsible_accident").default(false),
    punishment_completed: boolean("punishment_completed").default(false),
    punishment_info: text("punishment_info"),
    is_reported: boolean("is_reported").default(false),
    need_update_hazard_list: boolean("need_update_hazard_list").default(false),
    need_update_safety_procedures: boolean("need_update_safety_procedures").default(false),
});

export type Accident = InferSelectModel<typeof accident>;
