CREATE TABLE `accident` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`happen_date` varchar(255) NOT NULL,
	`month` varchar(255) NOT NULL,
	`oa_number` varchar(255) NOT NULL,
	`oa_submit_date` varchar(255) NOT NULL,
	`product_line` varchar(255) NOT NULL,
	`detail_place` varchar(255) NOT NULL,
	`self_ignite_cell_type` varchar(255) NOT NULL,
	`self_ignite_cell_number` int NOT NULL,
	`battery_self_ignite_reason` varchar(500) NOT NULL,
	`detail_content` text NOT NULL,
	`accident_or_event` varchar(50) NOT NULL,
	`accident_cause` varchar(500),
	`accident_type` varchar(255),
	`economic_loss` varchar(255),
	`work_hours_loss` varchar(255),
	`accident_level` varchar(50),
	`internal_or_related` varchar(50),
	`is_traffic_accident` boolean DEFAULT false,
	`is_fire_event` boolean DEFAULT false,
	`is_smoke_fire_attempt` boolean DEFAULT false,
	`event_cause` varchar(500),
	`event_type` varchar(255),
	`event_economic_loss` varchar(255),
	`attempt_classification` varchar(255),
	`direct_cause_type` varchar(255),
	`detail_content1` text,
	`indirect_cause_type` varchar(255),
	`detail_content2` text,
	`system_cause_type` varchar(255),
	`detail_content3` text,
	`corrective_measures` text,
	`completion_status` varchar(255),
	`is_responsible_accident` boolean DEFAULT false,
	`punishment_completed` boolean DEFAULT false,
	`punishment_info` text,
	`is_reported` boolean DEFAULT false,
	`need_update_hazard_list` boolean DEFAULT false,
	`need_update_safety_procedures` boolean DEFAULT false,
	CONSTRAINT `accident_id` PRIMARY KEY(`id`)
);
