import { Geist, Geist_Mono } from "next/font/google";
import "@ant-design/v5-patch-for-react-19";
import zhCN from "antd/locale/zh_CN";
import { ConfigProvider, App } from "antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Providers } from "./providers";
import "./globals.css";
import dayjs from "dayjs";
import "dayjs/locale/zh-cn";

dayjs.locale("zh-cn");

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "EHS",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ConfigProvider
                    locale={zhCN}
                    theme={{
                        cssVar: true,
                        hashed: false,
                        token: {},
                        components: {
                            Button: {
                                defaultBorderColor: "#0958d9",
                                defaultColor: "#0958d9",
                            },
                        },
                    }}
                >
                    <AntdRegistry>
                        <App>
                            <Providers>{children}</Providers>
                        </App>
                    </AntdRegistry>
                </ConfigProvider>
            </body>
        </html>
    );
}
